<?php

abstract class BaseController
{

    protected $model;

    protected function model($modelName)
    {
        $this->model = new $modelName;
        return $this->model;
    }

    /**
     * call the isValid method of the current model
     *
     * @param  [type]  $post_data [description]
     * @return boolean            [description]
     */
    protected function isValid($post_data){
        return $this->model->isValid($post_data);
    }

    /**
     * get from the model any errors that were generated by running validation
     *
     * @return array array of error messages
     */
    protected function getValidationErrors()
    {
        return $this->model->getValidationErrors();
    }

    /**
     * this is super primitive...
     * Should create a View class to be instantiated and used here
     * ...something that has methods to take view file name, view data, and then attempt to render a view
     *
     * @param  [type] $view [description]
     * @param  array  $data [description]
     * @return [type]       [description]
     */
    protected function view($view, $data = [])
    {
        require_once '../app/views/' . $view . '.php';
    }

    /**
     * return the current request object
     * (to access methods for getting post vars etc)
     *
     * @return object
     */
    public function getRequest()
    {
        return Request::getInstance();
    }

}
